{
 "title": "Kamon 2.0 Akka",
 "description": "Kamon 2.0 and Akka Dashboard using Prometheus as Datasource",
 "tags": [
  "Kamon",
  "Akka",
  "prometheus"
 ],
 "time": { "from": "now-15m", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "instance",
    "label": "Instance",
    "query": "label_values(akka_system_unhandled_messages_total,instance)"
   },
   {
    "name": "interval",
    "label": "Interval",
    "query": "1m,5m,10m,30m,1h,6h,12h,1d,7d,14d,30d"
   },
   { "name": "percentile", "label": "Percentile", "query": "0.5,0.90,0.95,0.99,0.999" },
   {
    "name": "system",
    "query": "label_values(akka_system_unhandled_messages_total, system)"
   }
  ]
 },
 "panels": [
  { "title": "Akka System Metrics", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Unhandled Messages",
   "type": "singlestat",
   "gridPos": { "h": 5, "w": 4, "x": 0, "y": 1 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": " sum(rate(akka_system_unhandled_messages_total{instance=~\"$instance\", system=~\"$system\"}[$interval])) by (system)"
    }
   ]
  },
  {
   "title": "Dead Letters",
   "type": "singlestat",
   "gridPos": { "h": 5, "w": 4, "x": 4, "y": 1 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum(rate(akka_system_dead_letters_total{instance=~\"$instance\", system=~\"$system\"}[$interval])) by (system)"
    }
   ]
  },
  {
   "type": "table",
   "gridPos": { "h": 5, "w": 6, "x": 8, "y": 1 },
   "targets": [
    {
     "expr": "sum(rate(akka_system_active_actors_count{instance=~\"$instance\", system=~\"$system\"}[$interval])) by (system)",
     "legendFormat": "Active Actors"
    },
    {
     "expr": "sum(irate(akka_system_processed_messages_total{instance=~\"$instance\",tracked=\"true\", system=~\"$system\"}[$interval])) by (system)",
     "legendFormat": "Processed Messages (tracked=true)"
    },
    {
     "expr": "sum(irate(akka_system_processed_messages_total{instance=~\"$instance\",tracked=\"false\", system=~\"$system\"}[$interval])) by (system)",
     "legendFormat": "Processed Messages (tracked=false)"
    }
   ]
  },
  {
   "title": "Errors",
   "type": "graph",
   "gridPos": { "h": 5, "w": 10, "x": 14, "y": 1 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    { "expr": "akka_group_errors_total", "legendFormat": "{{group}}" }
   ]
  },
  { "title": "Akka Http Metrics", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 6 } },
  {
   "title": "Processing Time ($percentile)",
   "type": "graph",
   "gridPos": { "h": 11, "w": 12, "x": 0, "y": 7 },
   "yaxes": [
    { "format": "short", "label": "Milliseconds" }
   ],
   "targets": [
    {
     "expr": "histogram_quantile($percentile, sum(rate(span_processing_time_seconds_bucket{instance=~\"$instance\"}[$interval])) by (le,operation,span_kind,error)) * 1000",
     "legendFormat": "{{ span_kind }}:{{ operation }} (error={{ error }})"
    }
   ]
  },
  {
   "title": "Active Requests",
   "type": "graph",
   "gridPos": { "h": 11, "w": 6, "x": 12, "y": 7 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "rate(http_server_request_active_sum{instance=~\"$instance\"}[$interval]) / rate(http_server_request_active_count{instance=~\"$instance\"}[$interval])",
     "legendFormat": "{{ instance }}: {{ interface }}:{{ port }}"
    }
   ]
  },
  {
   "title": "Open Connections",
   "type": "graph",
   "gridPos": { "h": 11, "w": 6, "x": 18, "y": 7 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "rate(http_server_connection_open_sum{instance=~\"$instance\"}[$interval]) / rate(http_server_connection_open_count{instance=~\"$instance\"}[$interval])",
     "legendFormat": "{{ instance }}: {{ interface }}:{{ port }}"
    }
   ]
  },
  { "title": "Akka Actor Metrics", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 18 } },
  {
   "title": "Processing Time ($percentile)",
   "type": "graph",
   "gridPos": { "h": 10, "w": 12, "x": 0, "y": 19 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "histogram_quantile($percentile, sum(rate(akka_actor_processing_time_seconds_bucket{instance=~\"$instance\"}[$interval])) by (le, path))",
     "legendFormat": "{{path}}"
    }
   ]
  },
  {
   "title": "Time in Mailbox ($percentile)",
   "type": "graph",
   "gridPos": { "h": 10, "w": 6, "x": 12, "y": 19 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "histogram_quantile($percentile, sum(rate(akka_actor_time_in_mailbox_seconds_bucket{instance=~\"$instance\"}[$interval])) by (le))",
     "legendFormat": "{{path}}"
    }
   ]
  },
  {
   "title": "Mailbox Size",
   "type": "graph",
   "gridPos": { "h": 10, "w": 6, "x": 18, "y": 19 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(rate(akka_actor_mailbox_size_sum{instance=~\"$instance\",class=~\"$class\",path=~\"$path\"}[$interval])) by (path) / sum(rate(akka_actor_mailbox_size_count{instance=~\"$instance\",class=~\"$class\",path=~\"$path\"}[$interval])) by (path)",
     "legendFormat": "{{path}}"
    }
   ]
  },
  { "title": "Akka Group Metrics", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 29 } },
  {
   "title": "Processing Time ($percentile)",
   "type": "graph",
   "gridPos": { "h": 10, "w": 12, "x": 0, "y": 30 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "histogram_quantile($percentile, sum(rate(akka_group_processing_time_seconds_bucket{instance=~\"$instance\"}[$interval])) by (le, group)) * 1000",
     "legendFormat": "{{group}}"
    }
   ]
  },
  {
   "title": "Time in Mailbox ($percentile)",
   "type": "graph",
   "gridPos": { "h": 10, "w": 6, "x": 12, "y": 30 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "histogram_quantile($percentile, sum(rate(akka_group_time_in_mailbox_seconds_bucket{instance=~\"$instance\"}[$interval])) by (le, group))",
     "legendFormat": "{{group}}"
    }
   ]
  },
  {
   "title": "Mailbox Size / Number of Members",
   "type": "graph",
   "gridPos": { "h": 10, "w": 6, "x": 18, "y": 30 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "rate(akka_group_mailbox_size_sum{instance=~\"$instance\"}[$interval]) / rate(akka_group_mailbox_size_count{instance=~\"$instance\"}[$interval])",
     "legendFormat": "{{group}} mailbox"
    },
    {
     "expr": "rate(akka_group_members_sum{instance=~\"$instance\"}[$interval]) / rate(akka_group_members_count{instance=~\"$instance\"}[$interval])",
     "legendFormat": "members of {{group}} "
    }
   ]
  },
  { "title": "Akka Router Metrics", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 40 } },
  {
   "title": "Processing Time ($percentile)",
   "type": "graph",
   "gridPos": { "h": 6, "w": 8, "x": 0, "y": 41 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "histogram_quantile($percentile, sum(rate(akka_router_processing_time_seconds_bucket{path=~\"$path\",instance=~\"$instance\"}[$interval])) by (le, path))",
     "legendFormat": "{{path}}"
    }
   ]
  },
  {
   "title": "Time in Mailbox ($percentile)",
   "type": "graph",
   "gridPos": { "h": 6, "w": 8, "x": 8, "y": 41 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "histogram_quantile($percentile, sum(irate(akka_router_time_in_mailbox_seconds_bucket{instance=~\"$instance\",path=~\"$path\"}[$interval])) by (le, path))",
     "legendFormat": "{{path}}"
    }
   ]
  },
  {
   "title": "Routing Time ($percentile)",
   "type": "graph",
   "gridPos": { "h": 6, "w": 8, "x": 16, "y": 41 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "histogram_quantile($percentile, sum(irate(akka_router_routing_time_seconds_bucket{path=~\"$path\",instance=~\"$instance\"}[$interval])) by (le, path))",
     "legendFormat": "{{path}}"
    }
   ]
  },
  {
   "title": "Akka Remote Metrics",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 47 },
   "collapsed": true,
   "panels": [
    {
     "title": "Serialization Time ($percentile)",
     "type": "graph",
     "gridPos": { "h": 11, "w": 12, "x": 0, "y": 73 },
     "yaxes": [
      { "format": "s" }
     ],
     "targets": [
      {
       "expr": "histogram_quantile($percentile, rate(akka_remote_serialization_time_seconds_bucket{instance=~\"$instance\"}[$interval]))",
       "legendFormat": "{{instance}} - {{direction}}"
      }
     ]
    },
    {
     "title": "Message Size",
     "type": "graph",
     "gridPos": { "h": 11, "w": 12, "x": 12, "y": 73 },
     "yaxes": [
      { "format": "decbytes" }
     ],
     "targets": [
      {
       "expr": "sum(rate(akka_remote_messages_inbound_size_bytes_sum{instance=~\"$instance\"}[$interval])) by (instance,direction) / sum(rate(akka_remote_messages_inbound_size_bytes_count{instance=~\"$instance\"}[$interval])) by (instance,direction)",
       "legendFormat": "{{ instance }} - {{ direction }}"
      }
     ]
    }
   ]
  },
  { "title": "Executor Metrics", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 48 } },
  {
   "title": "Number Of Threads",
   "type": "graph",
   "gridPos": { "h": 6, "w": 8, "x": 0, "y": 49 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "rate(executor_threads_total_count{instance=~\"$instance\"}[$interval]) / rate(executor_threads_total_sum{instance=~\"$instance\"}[$interval])",
     "legendFormat": "System:{{akka_system}} - Name: {{name}} - Type: {{type}}"
    }
   ]
  },
  {
   "title": "Number Of Tasks Completed",
   "type": "graph",
   "gridPos": { "h": 6, "w": 8, "x": 8, "y": 49 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "rate(executor_tasks_completed_total{instance=~\"$instance\"}[$interval])",
     "legendFormat": "{{ instance }}: {{ name }} ({{ type }}) {{akka_system}}"
    }
   ]
  },
  {
   "title": "Queue Size",
   "type": "graph",
   "gridPos": { "h": 6, "w": 8, "x": 16, "y": 49 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "rate(executor_queue_size_bucket{instance=~\"$instance\", le=\"+Inf\"}[$interval])",
     "legendFormat": "{{ akka_system }}: {{ name }} ({{ type }})"
    }
   ]
  },
  {
   "title": "Maximum Number of Threads",
   "type": "graph",
   "description": "Tracks executor maximum number of Threads",
   "gridPos": { "h": 6, "w": 8, "x": 0, "y": 55 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "executor_threads_max{instance=~\"$instance\"}",
     "legendFormat": "System: {{akka_system}} - Name: {{name}} - Type: {{type}}"
    }
   ]
  },
  {
   "title": "Minimum Number of Threads",
   "type": "graph",
   "description": "Tracks executor minimum number of Threads",
   "gridPos": { "h": 6, "w": 8, "x": 8, "y": 55 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "executor_threads_min{instance=~\"$instance\"}",
     "legendFormat": "System: {{akka_system}} - Name: {{name}} - Type: {{type}}"
    }
   ]
  },
  {
   "title": "Executor parallelism",
   "type": "graph",
   "description": "Tracks executor parallelism",
   "gridPos": { "h": 6, "w": 8, "x": 16, "y": 55 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "executor_parallelism{instance=~\"$instance\"}",
     "legendFormat": "System: {{akka_system}} - Name: {{name}} - Type: {{type}}"
    }
   ]
  },
  { "title": "JVM Metrics", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 61 } },
  {
   "title": "Garbage Collection",
   "type": "graph",
   "description": "Tracks the distribution of GC events duration",
   "gridPos": { "h": 5, "w": 12, "x": 0, "y": 62 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "rate(jvm_gc_seconds_sum{instance=~\"$instance\"}[2m])/rate(jvm_gc_seconds_count{ instance =~\"$instance\"}[2m])",
     "legendFormat": " {{instance}}  GC count: {{collector}}"
    }
   ]
  },
  {
   "title": "Heap",
   "type": "graph",
   "gridPos": { "h": 5, "w": 12, "x": 12, "y": 62 },
   "yaxes": [
    { "format": "decbytes" }
   ],
   "targets": [
    {
     "expr": "jvm_memory_max_bytes{instance=~\"$instance\", region=\"heap\"}",
     "legendFormat": "Max"
    },
    {
     "expr": "jvm_memory_committed_bytes{instance=~\"$instance\", region=\"heap\"}",
     "legendFormat": "Commited"
    },
    {
     "expr": "jvm_memory_used_bytes_sum{instance=~\"$instance\", region=\"heap\"} / jvm_memory_used_bytes_count{instance=~\"$instance\", region=\"heap\"}",
     "legendFormat": "Used"
    }
   ]
  },
  { "title": "Host Metrics", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 67 } },
  {
   "title": "Free Memory",
   "type": "singlestat",
   "description": "Tracks the amount of free memory",
   "gridPos": { "h": 5, "w": 3, "x": 0, "y": 68 },
   "format": "decbytes",
   "valueName": "avg",
   "targets": [
    { "expr": "host_memory_free_bytes" }
   ]
  },
  {
   "title": "Host Memory",
   "type": "graph",
   "description": "Tracks the total memory available vs  the amount of used memory\n",
   "gridPos": { "h": 5, "w": 10, "x": 3, "y": 68 },
   "yaxes": [
    { "format": "decbytes" }
   ],
   "targets": [
    {
     "expr": "host_memory_used_bytes{instance=~\"$instance\"}",
     "legendFormat": "Used Memory"
    },
    {
     "expr": "host_memory_total_bytes{instance=~\"$instance\"}",
     "legendFormat": "Total Memory"
    }
   ]
  },
  {
   "title": "System load average",
   "type": "graph",
   "description": "Tracks the system load average",
   "gridPos": { "h": 10, "w": 11, "x": 13, "y": 68 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "host_load_average{instance=~\"$instance\", period=\"1m\"}",
     "legendFormat": "host load average"
    }
   ]
  },
  {
   "title": "Free Swap Memory",
   "type": "singlestat",
   "description": "Tracks the free Swap space",
   "gridPos": { "h": 5, "w": 3, "x": 0, "y": 73 },
   "format": "bytes",
   "valueName": "avg",
   "targets": [
    {
     "expr": "host_swap_free_bytes{instance=~\"$instance\"}"
    }
   ]
  },
  {
   "title": "Swap Memory",
   "type": "graph",
   "gridPos": { "h": 5, "w": 10, "x": 3, "y": 73 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "host_swap_used_bytes{instance=~\"$instance\"}",
     "legendFormat": "Used Swap Memory"
    },
    {
     "expr": "host_swap_total_bytes{instance=~\"$instance\"}",
     "legendFormat": "Total Swap Memory"
    }
   ]
  }
 ]
}